#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="proyecto")]
public partial class DBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertusuario(usuario instance);
  partial void Updateusuario(usuario instance);
  partial void Deleteusuario(usuario instance);
  partial void Insertproveedores(proveedores instance);
  partial void Updateproveedores(proveedores instance);
  partial void Deleteproveedores(proveedores instance);
  partial void Insertmarca(marca instance);
  partial void Updatemarca(marca instance);
  partial void Deletemarca(marca instance);
  partial void Insertsuscriptore(suscriptore instance);
  partial void Updatesuscriptore(suscriptore instance);
  partial void Deletesuscriptore(suscriptore instance);
  partial void Insertcategoria(categoria instance);
  partial void Updatecategoria(categoria instance);
  partial void Deletecategoria(categoria instance);
  partial void Insertproducto(producto instance);
  partial void Updateproducto(producto instance);
  partial void Deleteproducto(producto instance);
  partial void Insertcliente(cliente instance);
  partial void Updatecliente(cliente instance);
  partial void Deletecliente(cliente instance);
  #endregion
	
	public DBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["proyectoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<usuario> usuarios
	{
		get
		{
			return this.GetTable<usuario>();
		}
	}
	
	public System.Data.Linq.Table<proveedores> proveedores
	{
		get
		{
			return this.GetTable<proveedores>();
		}
	}
	
	public System.Data.Linq.Table<marca> marcas
	{
		get
		{
			return this.GetTable<marca>();
		}
	}
	
	public System.Data.Linq.Table<suscriptore> suscriptores
	{
		get
		{
			return this.GetTable<suscriptore>();
		}
	}
	
	public System.Data.Linq.Table<categoria> categorias
	{
		get
		{
			return this.GetTable<categoria>();
		}
	}
	
	public System.Data.Linq.Table<producto> productos
	{
		get
		{
			return this.GetTable<producto>();
		}
	}
	
	public System.Data.Linq.Table<cliente> clientes
	{
		get
		{
			return this.GetTable<cliente>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarUsuario")]
	public int agregarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, ape, usu, pass);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarUsuario")]
	public int eliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarUsuario")]
	public int modificarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, ape, usu, pass);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCliente")]
	public int eliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarCategoria")]
	public int agregarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cate);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCategoria")]
	public int eliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarCategoria")]
	public int modificarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, cate);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarProveedor")]
	public int eliminarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarProveedor")]
	public int agregarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string eMail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string direccion)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, telefono, eMail, direccion);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarProveedor")]
	public int modificarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string eMail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string direccion)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, nombre, telefono, eMail, direccion);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarMarca")]
	public int agregarMarca([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPro)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), marca, idPro);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarMarca")]
	public int eliminarMarca([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarMarca")]
	public int modificarMarca([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPro)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, idPro);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarSuscriptor")]
	public int modificarSuscriptor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, email);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarSuscriptor")]
	public int agregarSuscriptor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, email);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarSuscriptor")]
	public int eliminarSuscriptor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarProducto")]
	public int eliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarProducto")]
	public int agregarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMarca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string publico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string imagen)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, descripcion, idCategoria, idMarca, modelo, precio, stock, publico, imagen);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarProducto")]
	public int modificarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMarca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string publico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string imagen)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, nombre, descripcion, idCategoria, idMarca, modelo, precio, stock, publico, imagen);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarCliente")]
	public int agregarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, ape, genero, nacimiento, email, pass);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarCliente")]
	public int modificarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, ape, genero, nacimiento, email, pass);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idUsuario;
	
	private string _nombre;
	
	private string _apellidos;
	
	private string _usuario1;
	
	private string _contraseña;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
	
	public usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idUsuario
	{
		get
		{
			return this._idUsuario;
		}
		set
		{
			if ((this._idUsuario != value))
			{
				this.OnidUsuarioChanging(value);
				this.SendPropertyChanging();
				this._idUsuario = value;
				this.SendPropertyChanged("idUsuario");
				this.OnidUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="NVarChar(25)")]
	public string apellidos
	{
		get
		{
			return this._apellidos;
		}
		set
		{
			if ((this._apellidos != value))
			{
				this.OnapellidosChanging(value);
				this.SendPropertyChanging();
				this._apellidos = value;
				this.SendPropertyChanged("apellidos");
				this.OnapellidosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string usuario1
	{
		get
		{
			return this._usuario1;
		}
		set
		{
			if ((this._usuario1 != value))
			{
				this.Onusuario1Changing(value);
				this.SendPropertyChanging();
				this._usuario1 = value;
				this.SendPropertyChanged("usuario1");
				this.Onusuario1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string contraseña
	{
		get
		{
			return this._contraseña;
		}
		set
		{
			if ((this._contraseña != value))
			{
				this.OncontraseñaChanging(value);
				this.SendPropertyChanging();
				this._contraseña = value;
				this.SendPropertyChanged("contraseña");
				this.OncontraseñaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proveedores")]
public partial class proveedores : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idProveedor;
	
	private string _nombre;
	
	private string _telefono;
	
	private string _eMail;
	
	private string _direccion;
	
	private EntitySet<marca> _marcas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProveedorChanging(int value);
    partial void OnidProveedorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
	
	public proveedores()
	{
		this._marcas = new EntitySet<marca>(new Action<marca>(this.attach_marcas), new Action<marca>(this.detach_marcas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idProveedor
	{
		get
		{
			return this._idProveedor;
		}
		set
		{
			if ((this._idProveedor != value))
			{
				this.OnidProveedorChanging(value);
				this.SendPropertyChanging();
				this._idProveedor = value;
				this.SendPropertyChanged("idProveedor");
				this.OnidProveedorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(25)")]
	public string telefono
	{
		get
		{
			return this._telefono;
		}
		set
		{
			if ((this._telefono != value))
			{
				this.OntelefonoChanging(value);
				this.SendPropertyChanging();
				this._telefono = value;
				this.SendPropertyChanged("telefono");
				this.OntelefonoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(50)")]
	public string eMail
	{
		get
		{
			return this._eMail;
		}
		set
		{
			if ((this._eMail != value))
			{
				this.OneMailChanging(value);
				this.SendPropertyChanging();
				this._eMail = value;
				this.SendPropertyChanged("eMail");
				this.OneMailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string direccion
	{
		get
		{
			return this._direccion;
		}
		set
		{
			if ((this._direccion != value))
			{
				this.OndireccionChanging(value);
				this.SendPropertyChanging();
				this._direccion = value;
				this.SendPropertyChanged("direccion");
				this.OndireccionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_marca", Storage="_marcas", ThisKey="idProveedor", OtherKey="idProveedor")]
	public EntitySet<marca> marcas
	{
		get
		{
			return this._marcas;
		}
		set
		{
			this._marcas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_marcas(marca entity)
	{
		this.SendPropertyChanging();
		entity.proveedores = this;
	}
	
	private void detach_marcas(marca entity)
	{
		this.SendPropertyChanging();
		entity.proveedores = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.marcas")]
public partial class marca : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idMarca;
	
	private string _nombre;
	
	private int _idProveedor;
	
	private EntitySet<producto> _productos;
	
	private EntityRef<proveedores> _proveedores;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMarcaChanging(int value);
    partial void OnidMarcaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnidProveedorChanging(int value);
    partial void OnidProveedorChanged();
    #endregion
	
	public marca()
	{
		this._productos = new EntitySet<producto>(new Action<producto>(this.attach_productos), new Action<producto>(this.detach_productos));
		this._proveedores = default(EntityRef<proveedores>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarca", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idMarca
	{
		get
		{
			return this._idMarca;
		}
		set
		{
			if ((this._idMarca != value))
			{
				this.OnidMarcaChanging(value);
				this.SendPropertyChanging();
				this._idMarca = value;
				this.SendPropertyChanged("idMarca");
				this.OnidMarcaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="Int NOT NULL")]
	public int idProveedor
	{
		get
		{
			return this._idProveedor;
		}
		set
		{
			if ((this._idProveedor != value))
			{
				if (this._proveedores.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidProveedorChanging(value);
				this.SendPropertyChanging();
				this._idProveedor = value;
				this.SendPropertyChanged("idProveedor");
				this.OnidProveedorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="marca_producto", Storage="_productos", ThisKey="idMarca", OtherKey="idMarca")]
	public EntitySet<producto> productos
	{
		get
		{
			return this._productos;
		}
		set
		{
			this._productos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_marca", Storage="_proveedores", ThisKey="idProveedor", OtherKey="idProveedor", IsForeignKey=true)]
	public proveedores proveedores
	{
		get
		{
			return this._proveedores.Entity;
		}
		set
		{
			proveedores previousValue = this._proveedores.Entity;
			if (((previousValue != value) 
						|| (this._proveedores.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._proveedores.Entity = null;
					previousValue.marcas.Remove(this);
				}
				this._proveedores.Entity = value;
				if ((value != null))
				{
					value.marcas.Add(this);
					this._idProveedor = value.idProveedor;
				}
				else
				{
					this._idProveedor = default(int);
				}
				this.SendPropertyChanged("proveedores");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_productos(producto entity)
	{
		this.SendPropertyChanging();
		entity.marca = this;
	}
	
	private void detach_productos(producto entity)
	{
		this.SendPropertyChanging();
		entity.marca = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.suscriptores")]
public partial class suscriptore : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idSuscriptor;
	
	private string _nombre;
	
	private string _eMail;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSuscriptorChanging(int value);
    partial void OnidSuscriptorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    #endregion
	
	public suscriptore()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSuscriptor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idSuscriptor
	{
		get
		{
			return this._idSuscriptor;
		}
		set
		{
			if ((this._idSuscriptor != value))
			{
				this.OnidSuscriptorChanging(value);
				this.SendPropertyChanging();
				this._idSuscriptor = value;
				this.SendPropertyChanged("idSuscriptor");
				this.OnidSuscriptorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(50)")]
	public string eMail
	{
		get
		{
			return this._eMail;
		}
		set
		{
			if ((this._eMail != value))
			{
				this.OneMailChanging(value);
				this.SendPropertyChanging();
				this._eMail = value;
				this.SendPropertyChanged("eMail");
				this.OneMailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categorias")]
public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idCategoria;
	
	private string _nombre;
	
	private EntitySet<producto> _productos;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
	
	public categoria()
	{
		this._productos = new EntitySet<producto>(new Action<producto>(this.attach_productos), new Action<producto>(this.detach_productos));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idCategoria
	{
		get
		{
			return this._idCategoria;
		}
		set
		{
			if ((this._idCategoria != value))
			{
				this.OnidCategoriaChanging(value);
				this.SendPropertyChanging();
				this._idCategoria = value;
				this.SendPropertyChanged("idCategoria");
				this.OnidCategoriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_productos", ThisKey="idCategoria", OtherKey="idCategoria")]
	public EntitySet<producto> productos
	{
		get
		{
			return this._productos;
		}
		set
		{
			this._productos.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_productos(producto entity)
	{
		this.SendPropertyChanging();
		entity.categoria = this;
	}
	
	private void detach_productos(producto entity)
	{
		this.SendPropertyChanging();
		entity.categoria = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productos")]
public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idProducto;
	
	private string _nombre;
	
	private string _descripcion;
	
	private int _idCategoria;
	
	private int _idMarca;
	
	private string _modelo;
	
	private System.Nullable<decimal> _precio;
	
	private System.Nullable<int> _stock;
	
	private string _publico;
	
	private string _imagen;
	
	private EntityRef<categoria> _categoria;
	
	private EntityRef<marca> _marca;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductoChanging(int value);
    partial void OnidProductoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OnidMarcaChanging(int value);
    partial void OnidMarcaChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnstockChanging(System.Nullable<int> value);
    partial void OnstockChanged();
    partial void OnpublicoChanging(string value);
    partial void OnpublicoChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    #endregion
	
	public producto()
	{
		this._categoria = default(EntityRef<categoria>);
		this._marca = default(EntityRef<marca>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idProducto
	{
		get
		{
			return this._idProducto;
		}
		set
		{
			if ((this._idProducto != value))
			{
				this.OnidProductoChanging(value);
				this.SendPropertyChanging();
				this._idProducto = value;
				this.SendPropertyChanged("idProducto");
				this.OnidProductoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this.OndescripcionChanging(value);
				this.SendPropertyChanging();
				this._descripcion = value;
				this.SendPropertyChanged("descripcion");
				this.OndescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
	public int idCategoria
	{
		get
		{
			return this._idCategoria;
		}
		set
		{
			if ((this._idCategoria != value))
			{
				if (this._categoria.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidCategoriaChanging(value);
				this.SendPropertyChanging();
				this._idCategoria = value;
				this.SendPropertyChanged("idCategoria");
				this.OnidCategoriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarca", DbType="Int NOT NULL")]
	public int idMarca
	{
		get
		{
			return this._idMarca;
		}
		set
		{
			if ((this._idMarca != value))
			{
				if (this._marca.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidMarcaChanging(value);
				this.SendPropertyChanging();
				this._idMarca = value;
				this.SendPropertyChanged("idMarca");
				this.OnidMarcaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="NVarChar(50)")]
	public string modelo
	{
		get
		{
			return this._modelo;
		}
		set
		{
			if ((this._modelo != value))
			{
				this.OnmodeloChanging(value);
				this.SendPropertyChanging();
				this._modelo = value;
				this.SendPropertyChanged("modelo");
				this.OnmodeloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
	public System.Nullable<decimal> precio
	{
		get
		{
			return this._precio;
		}
		set
		{
			if ((this._precio != value))
			{
				this.OnprecioChanging(value);
				this.SendPropertyChanging();
				this._precio = value;
				this.SendPropertyChanged("precio");
				this.OnprecioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
	public System.Nullable<int> stock
	{
		get
		{
			return this._stock;
		}
		set
		{
			if ((this._stock != value))
			{
				this.OnstockChanging(value);
				this.SendPropertyChanging();
				this._stock = value;
				this.SendPropertyChanged("stock");
				this.OnstockChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publico", DbType="VarChar(20)")]
	public string publico
	{
		get
		{
			return this._publico;
		}
		set
		{
			if ((this._publico != value))
			{
				this.OnpublicoChanging(value);
				this.SendPropertyChanging();
				this._publico = value;
				this.SendPropertyChanged("publico");
				this.OnpublicoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string imagen
	{
		get
		{
			return this._imagen;
		}
		set
		{
			if ((this._imagen != value))
			{
				this.OnimagenChanging(value);
				this.SendPropertyChanging();
				this._imagen = value;
				this.SendPropertyChanged("imagen");
				this.OnimagenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_categoria", ThisKey="idCategoria", OtherKey="idCategoria", IsForeignKey=true)]
	public categoria categoria
	{
		get
		{
			return this._categoria.Entity;
		}
		set
		{
			categoria previousValue = this._categoria.Entity;
			if (((previousValue != value) 
						|| (this._categoria.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._categoria.Entity = null;
					previousValue.productos.Remove(this);
				}
				this._categoria.Entity = value;
				if ((value != null))
				{
					value.productos.Add(this);
					this._idCategoria = value.idCategoria;
				}
				else
				{
					this._idCategoria = default(int);
				}
				this.SendPropertyChanged("categoria");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="marca_producto", Storage="_marca", ThisKey="idMarca", OtherKey="idMarca", IsForeignKey=true)]
	public marca marca
	{
		get
		{
			return this._marca.Entity;
		}
		set
		{
			marca previousValue = this._marca.Entity;
			if (((previousValue != value) 
						|| (this._marca.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._marca.Entity = null;
					previousValue.productos.Remove(this);
				}
				this._marca.Entity = value;
				if ((value != null))
				{
					value.productos.Add(this);
					this._idMarca = value.idMarca;
				}
				else
				{
					this._idMarca = default(int);
				}
				this.SendPropertyChanged("marca");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idCliente;
	
	private string _nombre;
	
	private string _apellidos;
	
	private string _genero;
	
	private System.Nullable<System.DateTime> _nacimiento;
	
	private string _eMail;
	
	private string _contraseña;
	
	private System.DateTime _fechaRegistro;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OngeneroChanging(string value);
    partial void OngeneroChanged();
    partial void OnnacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnnacimientoChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    #endregion
	
	public cliente()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idCliente
	{
		get
		{
			return this._idCliente;
		}
		set
		{
			if ((this._idCliente != value))
			{
				this.OnidClienteChanging(value);
				this.SendPropertyChanging();
				this._idCliente = value;
				this.SendPropertyChanged("idCliente");
				this.OnidClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(25)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="NVarChar(25)")]
	public string apellidos
	{
		get
		{
			return this._apellidos;
		}
		set
		{
			if ((this._apellidos != value))
			{
				this.OnapellidosChanging(value);
				this.SendPropertyChanging();
				this._apellidos = value;
				this.SendPropertyChanged("apellidos");
				this.OnapellidosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="NVarChar(25)")]
	public string genero
	{
		get
		{
			return this._genero;
		}
		set
		{
			if ((this._genero != value))
			{
				this.OngeneroChanging(value);
				this.SendPropertyChanging();
				this._genero = value;
				this.SendPropertyChanged("genero");
				this.OngeneroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacimiento", DbType="Date")]
	public System.Nullable<System.DateTime> nacimiento
	{
		get
		{
			return this._nacimiento;
		}
		set
		{
			if ((this._nacimiento != value))
			{
				this.OnnacimientoChanging(value);
				this.SendPropertyChanging();
				this._nacimiento = value;
				this.SendPropertyChanged("nacimiento");
				this.OnnacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(50)")]
	public string eMail
	{
		get
		{
			return this._eMail;
		}
		set
		{
			if ((this._eMail != value))
			{
				this.OneMailChanging(value);
				this.SendPropertyChanging();
				this._eMail = value;
				this.SendPropertyChanged("eMail");
				this.OneMailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string contraseña
	{
		get
		{
			return this._contraseña;
		}
		set
		{
			if ((this._contraseña != value))
			{
				this.OncontraseñaChanging(value);
				this.SendPropertyChanging();
				this._contraseña = value;
				this.SendPropertyChanged("contraseña");
				this.OncontraseñaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
	public System.DateTime fechaRegistro
	{
		get
		{
			return this._fechaRegistro;
		}
		set
		{
			if ((this._fechaRegistro != value))
			{
				this.OnfechaRegistroChanging(value);
				this.SendPropertyChanging();
				this._fechaRegistro = value;
				this.SendPropertyChanged("fechaRegistro");
				this.OnfechaRegistroChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
